int NUMBEROFPIXELS = 2048
int SHOWOPENFILE = 1
int SHOWSCOPE = 2
int SHOWABSORBANCE = 3
int SHOWTRANSMISSION = 4
int SHOWREFERENCE = 5
int SHOWRADIANCE = 6
int SNAPSHOT = 7

int BOXCARNONE = 0
int BOXCAR5PIXEL = 1
int BOXCAR9PIXEL = 2
int BOXCAR17PIXEL = 3
int BOXCAR33PIXEL = 4
int LOW = 0
int MEDIUM = 1
int HIGH = 2